Repository getkirby/getkirby.com, pull requests merged in 2021-01, with the labels that each got.

#1141 Update migration recipe: route arguments
  content/1_docs/2_cookbook/9_setup/0_migrate-site/recipe.txt
Labels: type: content 📝

#1131 Redirects: easier to manage
  content/releases/link.txt
  site/config/redirects.php
  site/config/routes.php
  site/plugins/redirects/index.php
Labels: type: refactoring :recycle:

#1101 Setup refactor: remove backstop
  .gitignore
  README.md
  backstop.default.json
  package-lock.json
  package.json
  scripts/backstop-config
  site/plugins/backstop/index.php
Labels: type: refactoring :recycle:

#1145 Update CDN recipe
  content/1_docs/2_cookbook/7_extensions/0_kirby-loves-cdn/recipe.txt
  site/plugins/keycdn/index.php
Labels: type: content 📝

#1156 Moves the heading titles outside <since> tag
  content/1_docs/3_reference/3_panel/2_presets/0_files/cheatsheet-article.txt
  content/1_docs/3_reference/3_panel/3_fields/0_info/cheatsheet-article.txt
  content/1_docs/3_reference/3_panel/4_sections/0_fields/section.txt
  content/1_docs/3_reference/3_panel/4_sections/0_files/section.txt
  content/1_docs/3_reference/3_panel/4_sections/0_info/section.txt
  content/1_docs/3_reference/4_objects/0_file/0_srcset/method.txt
  content/1_docs/3_reference/4_objects/0_kirby/0_email/method.txt
  content/1_docs/3_reference/6_system/1_options/0_auth/cheatsheet-article.txt
  content/1_docs/3_reference/7_plugins/1_extensions/0_hooks/extension.txt
Labels: type: bug 🐛

#1065 Add quicktip repeated queries
  content/1_docs/2_cookbook/3_templating/0_keep_your_code_dry/recipe.txt
Labels: type: content 📝

#1161 Add recipe how to update blocks programmatically
  content/1_docs/2_cookbook/3_templating/0_update-blocks-programmatically/recipe.txt
Labels: type: content 📝

#1167 Fix search JS
  www/assets/js/components/search.js
  www/assets/js/index.js
Labels: type: refactoring :recycle:

#1168 Remove glossary tooltips
  site/plugins/maki/composer.lock
  site/plugins/maki/src/Glossary.php
  site/plugins/maki/tags.php
  site/plugins/maki/vendor/composer/ClassLoader.php
  site/plugins/maki/vendor/composer/InstalledVersions.php
  site/plugins/maki/vendor/composer/autoload_classmap.php
  site/plugins/maki/vendor/composer/autoload_real.php
  site/plugins/maki/vendor/composer/autoload_static.php
  site/plugins/maki/vendor/composer/installed.json
  site/plugins/maki/vendor/composer/installed.php
  site/snippets/cheatsheet.article.meta.php
  www/assets/css/legacy.css
  www/assets/js/components/tooltips.js
  www/assets/js/index.js
  www/assets/js/libraries/tippy.js
Labels: type: refactoring :recycle:

#1182 Algolia typo tolerance for all results page #1175
  site/controllers/search.php
Labels: type: bug 🐛

#1183 Integrate lightbox assets into normal setup
  package.json
  site/templates/v35.php
  www/assets/css/components/lightbox.css
  www/assets/css/templates/v35.css
  www/assets/js/components/lightbox.js
  www/assets/js/templates/v35.js
Labels: type: refactoring :recycle:

#1179 Minify clipboard.js
  www/assets/js/libraries/clipboard.js
Labels: type: refactoring :recycle:

#1177 Update lazysizes
  www/assets/js/libraries/lazysizes.js
Labels: type: refactoring :recycle:

#1178 Update prismjs
  www/assets/js/libraries/prism.js
Labels: type: refactoring :recycle:

#1186 Image compression workflow: ignore `kirby` folder
  .github/workflows/images.yml
Labels: type: refactoring :recycle:

#1173 Refactor search: remove dependencies
  site/snippets/cheatsheet.header.php
  site/snippets/search.php
  www/assets/css/legacy.css
  www/assets/css/templates/cheatsheet.css
  www/assets/js/components/search.js
  www/assets/js/index.js
  www/assets/js/libraries/algoliasearch.js
  www/assets/js/libraries/awesomplete.js
Labels: type: refactoring :recycle:

#1188 Adds video tag extended plugin
  site/plugins/video-tag-extended/index.php
Labels: type: feature ⭐️

#1193 Fixes the logs root directory #1191
  content/1_docs/3_reference/6_system/3_roots/0_log/root.txt
  content/1_docs/3_reference/6_system/3_roots/0_logs/root.txt
Labels: type: content 📝
