Repository getkirby/getkirby.com, pull requests merged in 2024-06, with the labels that each got.

#2319 Remove widont from titles
  site/templates/buzz-entry.php
  site/templates/cookbook-recipe.php
  site/templates/quicktip.php
Labels: type: bug 🐛, type: design 🌈

#2311 Quicktip: IDE support
  content/docs/4_quicktips/0_ide-support/quicktip.txt
Labels: type: content 📝

#2323 `img()` helper: fix widht/height attributes
  site/plugins/site/helpers/html.php
Labels: type: enhancement ✨

#2327 `FileVersion` for `cdn` plugin
  site/plugins/cdn/index.php
  site/plugins/cdn/src/FileVersion.php
Labels: type: bug 🐛

#2334 4.3 docs: named arguments
  content/docs/1_guide/17_plugins/1_custom-plugins/guide.txt
Labels: type: content 📝

#2339 Increase clickable area of menu links
  assets/css/site/footer.css
  assets/css/site/sidebar.css
Labels: type: design 🌈, type: refactoring :recycle:

#2341 Fix invalid markup in reference
  site/snippets/templates/reference/section.php
Labels: type: bug 🐛, type: refactoring :recycle:
